<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>d7e58c23-400d-4668-b7f3-1b3865839bfe</elementGuidId>
    <imagePath></imagePath>
    <name>link_AmazonPay</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/header[1]/div[1]/div[4]/div[2]/div[2]/div[1]/a[11]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/sva/dashboard?ref_=nav_cs_apay') and equals(@text,'Amazon Pay')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Amazon Pay"s]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/sva/dashboard?ref_=nav_cs_apay</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Amazon Pay</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
</WebElementEntity>