<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>73a35675-322a-4c86-836e-529fe3e241ce</elementGuidId>
    <imagePath></imagePath>
    <name>link_AnyDepartment2</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[1]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/bestsellers/ref=zg_bs_unv_apparel_0_1968083031_5') and equals(@text,'Any Department')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Any Department"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/bestsellers/ref=zg_bs_unv_apparel_0_1968083031_5</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Any Department</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
</WebElementEntity>