<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>5ad8809c-96ef-4c2e-bfd6-44870ba0ce25</elementGuidId>
    <imagePath></imagePath>
    <name>link_FilmSongs</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[9]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/bestsellers/music/1375845031/ref=zg_bs_nav_music_1_1375742031') and equals(@text,'Film Songs')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Film Songs"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/bestsellers/music/1375845031/ref=zg_bs_nav_music_1_1375742031</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Film Songs</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
</WebElementEntity>