<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>afec406c-3821-48d0-b316-b29cf336ed20</elementGuidId>
    <imagePath></imagePath>
    <name>link_SleepRobes</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[1]/div[2]/div[1]/div[1]/div[2]/div[1]/div[1]/div[2]/div[2]/div[2]/div[2]/div[4]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/gp/bestsellers/apparel/1968083031/ref=zg_bs_nav_apparel_3_1968082031') and equals(@text,'Sleep Robes')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Sleep Robes"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/gp/bestsellers/apparel/1968083031/ref=zg_bs_nav_apparel_3_1968082031</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Sleep Robes</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
</WebElementEntity>