<?xml version="1.0" encoding="utf-8"?>
<WebElementEntity>
    <description>Generated by Katalon AI</description>
    <elementGuidId>70bd37cb-e0b8-429c-a461-25c82f14b642</elementGuidId>
    <imagePath></imagePath>
    <name>link_AmazonPrimeVideo</name>
    <selectorCollection>
        <entry>
            <key>XPATH</key>
            <value>//body/div[3]/div[2]/div[2]/ul[3]/li[3]/a[1]</value>
        </entry>
        <entry>
            <key>BASIC</key>
            <value>//*[equals(@href,'/b?node=10882806031&amp;ref_=nav_em__shopall_Primevideo_0_2_3_2') and equals(@text,'Amazon Prime Video')]</value>
        </entry>
    </selectorCollection>
    <selectorMethod>XPATH</selectorMethod>
    <smartLocatorCollection>
        <entry>
            <key>SMART_LOCATOR</key>
            <value>internal:role=link[name="Amazon Prime Video"i]</value>
        </entry>
    </smartLocatorCollection>
    <smartLocatorEnabled>true</smartLocatorEnabled>
    <tag></tag>
    <useRalativeImagePath>false</useRalativeImagePath>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>href</name>
        <type>Main</type>
        <value>/b?node=10882806031&amp;ref_=nav_em__shopall_Primevideo_0_2_3_2</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
    <webElementProperties>
        <isSelected>true</isSelected>
        <matchCondition>equals</matchCondition>
        <name>text</name>
        <type>Main</type>
        <value>Amazon Prime Video</value>
        <webElementGuid>e63bf608-cc76-462f-8338-60f9e4d2f904</webElementGuid>
    </webElementProperties>
</WebElementEntity>